"""empty message

Revision ID: 05d4a598485c
Revises: 88df154ee637
Create Date: 2018-11-06 04:27:57.543382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d4a598485c'
down_revision = '88df154ee637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_idx', 'images', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='images')
    # ### end Alembic commands ###
