"""empty message

Revision ID: 0cbcdecf840a
Revises: 4e5f0423ed46
Create Date: 2018-08-10 01:39:11.961334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cbcdecf840a'
down_revision = '4e5f0423ed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_hash', sa.String(length=40), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('shop', sa.Text(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('spider_cat', sa.Text(), nullable=True),
    sa.Column('img_cats_ai_txt', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('img_cats_sc_txt', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('color_name', sa.Text(), nullable=True),
    sa.Column('color_512', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_1_hex', sa.String(), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2_hex', sa.String(), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3_hex', sa.String(), nullable=True),
    sa.Column('encoding_nocrop', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('encoding_crop', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('encoding_squarecrop', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_brand'), 'images', ['brand'], unique=False)
    op.create_index(op.f('ix_images_color_name'), 'images', ['color_name'], unique=False)
    op.create_index(op.f('ix_images_img_cats_ai_txt'), 'images', ['img_cats_ai_txt'], unique=False)
    op.create_index(op.f('ix_images_img_cats_sc_txt'), 'images', ['img_cats_sc_txt'], unique=False)
    op.create_index(op.f('ix_images_img_hash'), 'images', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_index(op.f('ix_images_spider_cat'), 'images', ['spider_cat'], unique=False)
    op.create_table('mainproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_hash', sa.String(length=40), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('shop', sa.Text(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('img_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('img_hashes', postgresql.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('spider_cat', sa.Text(), nullable=True),
    sa.Column('img_cats_sc_txt', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mainproducts_brand'), 'mainproducts', ['brand'], unique=False)
    op.create_index(op.f('ix_mainproducts_img_cats_sc_txt'), 'mainproducts', ['img_cats_sc_txt'], unique=False)
    op.create_index(op.f('ix_mainproducts_img_hashes'), 'mainproducts', ['img_hashes'], unique=False)
    op.create_index(op.f('ix_mainproducts_name'), 'mainproducts', ['name'], unique=False)
    op.create_index(op.f('ix_mainproducts_prod_hash'), 'mainproducts', ['prod_hash'], unique=True)
    op.create_index(op.f('ix_mainproducts_spider_cat'), 'mainproducts', ['spider_cat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mainproducts_spider_cat'), table_name='mainproducts')
    op.drop_index(op.f('ix_mainproducts_prod_hash'), table_name='mainproducts')
    op.drop_index(op.f('ix_mainproducts_name'), table_name='mainproducts')
    op.drop_index(op.f('ix_mainproducts_img_hashes'), table_name='mainproducts')
    op.drop_index(op.f('ix_mainproducts_img_cats_sc_txt'), table_name='mainproducts')
    op.drop_index(op.f('ix_mainproducts_brand'), table_name='mainproducts')
    op.drop_table('mainproducts')
    op.drop_index(op.f('ix_images_spider_cat'), table_name='images')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_img_hash'), table_name='images')
    op.drop_index(op.f('ix_images_img_cats_sc_txt'), table_name='images')
    op.drop_index(op.f('ix_images_img_cats_ai_txt'), table_name='images')
    op.drop_index(op.f('ix_images_color_name'), table_name='images')
    op.drop_index(op.f('ix_images_brand'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
