"""empty message

Revision ID: 15ac278246dc
Revises: 407126063091
Create Date: 2020-04-25 23:38:31.349486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ac278246dc'
down_revision = '407126063091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_hash')
    # ### end Alembic commands ###
