"""empty message

Revision ID: 252a45ba03c8
Revises: 995e9d1b7ad2
Create Date: 2018-10-07 22:07:44.286657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252a45ba03c8'
down_revision = '995e9d1b7ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('insta_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'insta_username')
    # ### end Alembic commands ###
