"""empty message

Revision ID: 37b0687eab49
Revises: 68c3b5849638
Create Date: 2019-10-18 11:52:58.638593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b0687eab49'
down_revision = '68c3b5849638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_fav', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_fav')
    # ### end Alembic commands ###
