"""empty message

Revision ID: 40652d47de28
Revises: 6aa328c92639
Create Date: 2020-03-07 19:54:52.286493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40652d47de28'
down_revision = '6aa328c92639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_skinny_men_a',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('img_hash', sa.String(length=40), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('img_skinny_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('img_hash')
    )
    op.create_index('images_skinny_men_a_name_idx', 'images_skinny_men_a', ['img_skinny_name'], unique=False, postgresql_ops={'img_skinny_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_skinny_men_a_all_cats'), 'images_skinny_men_a', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_men_a_img_hash'), 'images_skinny_men_a', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_skinny_men_a_img_skinny_name'), 'images_skinny_men_a', ['img_skinny_name'], unique=False)
    op.create_index(op.f('ix_images_skinny_men_a_kind_cats'), 'images_skinny_men_a', ['kind_cats'], unique=False)
    op.create_table('prods_men_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('color_string', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_hash', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.Text(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('is_fav', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prods_men_a_image_hash'), 'prods_men_a', ['image_hash'], unique=False)
    op.create_index(op.f('ix_prods_men_a_kind_cats'), 'prods_men_a', ['kind_cats'], unique=False)
    op.create_index(op.f('ix_prods_men_a_name'), 'prods_men_a', ['name'], unique=False)
    op.create_index(op.f('ix_prods_men_a_prod_id'), 'prods_men_a', ['prod_id'], unique=True)
    op.create_table('images_full_men_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_hash', sa.String(length=40), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('img_full_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_1_hex', sa.String(), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2_hex', sa.String(), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3_hex', sa.String(), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('encoding_vgg16', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['img_hash'], ['images_skinny_men_a.img_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('images_full_men_a_name_idx', 'images_full_men_a', ['img_full_name'], unique=False, postgresql_ops={'img_full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_full_men_a_all_cats'), 'images_full_men_a', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_full_men_a_img_full_name'), 'images_full_men_a', ['img_full_name'], unique=False)
    op.create_index(op.f('ix_images_full_men_a_img_hash'), 'images_full_men_a', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_full_men_a_kind_cats'), 'images_full_men_a', ['kind_cats'], unique=False)
    op.drop_index('ix_products_image_hash', table_name='products')
    op.drop_index('ix_products_kind_cats', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_prod_id', table_name='products')
    op.drop_table('products')
    op.drop_constraint('images_v2_skinny_img_hash_fkey', 'images_v2_skinny', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('images_v2_skinny_img_hash_fkey', 'images_v2_skinny', 'images_v2', ['img_hash'], ['img_hash'])
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('saleprice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('all_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('attr_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col_pat_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('color_pattern_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('color_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filter_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('image_hash', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('kind_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('material_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('prod_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('style_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_fav', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_index('ix_products_prod_id', 'products', ['prod_id'], unique=True)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_kind_cats', 'products', ['kind_cats'], unique=False)
    op.create_index('ix_products_image_hash', 'products', ['image_hash'], unique=False)
    op.drop_index(op.f('ix_images_full_men_a_kind_cats'), table_name='images_full_men_a')
    op.drop_index(op.f('ix_images_full_men_a_img_hash'), table_name='images_full_men_a')
    op.drop_index(op.f('ix_images_full_men_a_img_full_name'), table_name='images_full_men_a')
    op.drop_index(op.f('ix_images_full_men_a_all_cats'), table_name='images_full_men_a')
    op.drop_index('images_full_men_a_name_idx', table_name='images_full_men_a')
    op.drop_table('images_full_men_a')
    op.drop_index(op.f('ix_prods_men_a_prod_id'), table_name='prods_men_a')
    op.drop_index(op.f('ix_prods_men_a_name'), table_name='prods_men_a')
    op.drop_index(op.f('ix_prods_men_a_kind_cats'), table_name='prods_men_a')
    op.drop_index(op.f('ix_prods_men_a_image_hash'), table_name='prods_men_a')
    op.drop_table('prods_men_a')
    op.drop_index(op.f('ix_images_skinny_men_a_kind_cats'), table_name='images_skinny_men_a')
    op.drop_index(op.f('ix_images_skinny_men_a_img_skinny_name'), table_name='images_skinny_men_a')
    op.drop_index(op.f('ix_images_skinny_men_a_img_hash'), table_name='images_skinny_men_a')
    op.drop_index(op.f('ix_images_skinny_men_a_all_cats'), table_name='images_skinny_men_a')
    op.drop_index('images_skinny_men_a_name_idx', table_name='images_skinny_men_a')
    op.drop_table('images_skinny_men_a')
    # ### end Alembic commands ###
