"""empty message

Revision ID: 407126063091
Revises: acbb795d547f
Create Date: 2020-04-25 17:19:11.498641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407126063091'
down_revision = 'acbb795d547f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_full_men_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    op.add_column('images_full_women_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    op.add_column('images_skinny_men_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    op.add_column('images_skinny_women_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    op.add_column('prods_men_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    op.add_column('prods_women_a', sa.Column('date_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prods_women_a', 'date_updated')
    op.drop_column('prods_men_a', 'date_updated')
    op.drop_column('images_skinny_women_a', 'date_updated')
    op.drop_column('images_skinny_men_a', 'date_updated')
    op.drop_column('images_full_women_a', 'date_updated')
    op.drop_column('images_full_men_a', 'date_updated')
    # ### end Alembic commands ###
