"""empty message

Revision ID: 48b210f80d39
Revises: bc21c176a90f
Create Date: 2020-03-07 19:58:49.814597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48b210f80d39'
down_revision = 'bc21c176a90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_v2_skinny_all_cats', table_name='images_v2_skinny')
    op.drop_index('ix_images_v2_skinny_img_hash', table_name='images_v2_skinny')
    op.drop_index('ix_images_v2_skinny_img_name', table_name='images_v2_skinny')
    op.drop_index('ix_images_v2_skinny_kind_cats', table_name='images_v2_skinny')
    op.drop_index('name_idx_v2_skinny', table_name='images_v2_skinny')
    op.drop_table('images_v2_skinny')
    op.drop_index('ix_images_v2_all_cats', table_name='images_v2')
    op.drop_index('ix_images_v2_img_hash', table_name='images_v2')
    op.drop_index('ix_images_v2_img_name', table_name='images_v2')
    op.drop_index('ix_images_v2_kind_cats', table_name='images_v2')
    op.drop_index('name_idx_v2', table_name='images_v2')
    op.drop_table('images_v2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_v2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_string', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('saleprice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('color_pattern_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('kind_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('col_pat_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('style_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('material_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('attr_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('filter_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('all_arr', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('color_1_hex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('color_2_hex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('color_3_hex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('encoding_crop', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('encoding_vgg16', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='images_v2_pkey')
    )
    op.create_index('name_idx_v2', 'images_v2', ['img_name'], unique=False)
    op.create_index('ix_images_v2_kind_cats', 'images_v2', ['kind_cats'], unique=False)
    op.create_index('ix_images_v2_img_name', 'images_v2', ['img_name'], unique=False)
    op.create_index('ix_images_v2_img_hash', 'images_v2', ['img_hash'], unique=True)
    op.create_index('ix_images_v2_all_cats', 'images_v2', ['all_cats'], unique=False)
    op.create_table('images_v2_skinny',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_string', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('saleprice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('color_pattern_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('img_hash', name='images_v2_skinny_pkey')
    )
    op.create_index('name_idx_v2_skinny', 'images_v2_skinny', ['img_name'], unique=False)
    op.create_index('ix_images_v2_skinny_kind_cats', 'images_v2_skinny', ['kind_cats'], unique=False)
    op.create_index('ix_images_v2_skinny_img_name', 'images_v2_skinny', ['img_name'], unique=False)
    op.create_index('ix_images_v2_skinny_img_hash', 'images_v2_skinny', ['img_hash'], unique=True)
    op.create_index('ix_images_v2_skinny_all_cats', 'images_v2_skinny', ['all_cats'], unique=False)
    # ### end Alembic commands ###
