"""empty message

Revision ID: 4b381a994e9a
Revises: 56ff3d75986e
Create Date: 2020-01-29 14:48:23.751458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b381a994e9a'
down_revision = '56ff3d75986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'images_full_women_a', 'images_skinny_women_a', ['img_hash'], ['img_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images_full_women_a', type_='foreignkey')
    # ### end Alembic commands ###
