"""empty message

Revision ID: 4e5f0423ed46
Revises: fc050074dbdc
Create Date: 2018-07-04 16:54:50.820478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e5f0423ed46'
down_revision = 'fc050074dbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color_512', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('products', sa.Column('date', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('img_urls', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('pattern_256', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('products', sa.Column('spider_cat', sa.Text(), nullable=True))
    op.create_index(op.f('ix_products_img_cats_ai_txt'), 'products', ['img_cats_ai_txt'], unique=False)
    op.create_index(op.f('ix_products_spider_cat'), 'products', ['spider_cat'], unique=False)
    op.drop_index('ix_products_color_1_int', table_name='products')
    op.drop_index('ix_products_nr1_cat_ai', table_name='products')
    op.drop_index('ix_products_nr1_cat_sc', table_name='products')
    op.drop_column('products', 'img_cats_ai')
    op.drop_column('products', 'nr1_cat_sc')
    op.drop_column('products', 'img_cats_sc')
    op.drop_column('products', 'color_1_int')
    op.drop_column('products', 'nr1_cat_ai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('nr1_cat_ai', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('color_1_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('img_cats_sc', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('nr1_cat_sc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('img_cats_ai', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.create_index('ix_products_nr1_cat_sc', 'products', ['nr1_cat_sc'], unique=False)
    op.create_index('ix_products_nr1_cat_ai', 'products', ['nr1_cat_ai'], unique=False)
    op.create_index('ix_products_color_1_int', 'products', ['color_1_int'], unique=False)
    op.drop_index(op.f('ix_products_spider_cat'), table_name='products')
    op.drop_index(op.f('ix_products_img_cats_ai_txt'), table_name='products')
    op.drop_column('products', 'spider_cat')
    op.drop_column('products', 'pattern_256')
    op.drop_column('products', 'img_urls')
    op.drop_column('products', 'description')
    op.drop_column('products', 'date')
    op.drop_column('products', 'color_512')
    # ### end Alembic commands ###
