"""empty message

Revision ID: 60d64665c198
Revises: f8898e80094a
Create Date: 2020-04-03 13:05:50.683394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d64665c198'
down_revision = 'f8898e80094a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_full_men_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('images_full_women_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('images_skinny_men_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('images_skinny_women_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('prods_men_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('prods_women_a', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prods_women_a', 'is_deleted')
    op.drop_column('prods_men_a', 'is_deleted')
    op.drop_column('images_skinny_women_a', 'is_deleted')
    op.drop_column('images_skinny_men_a', 'is_deleted')
    op.drop_column('images_full_women_a', 'is_deleted')
    op.drop_column('images_full_men_a', 'is_deleted')
    # ### end Alembic commands ###
