"""empty message

Revision ID: 60dc94800ba4
Revises: 15ac278246dc
Create Date: 2020-05-23 14:19:29.965406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60dc94800ba4'
down_revision = '15ac278246dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_skinny_men_b',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('img_hash', sa.String(length=40), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('img_skinny_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('img_hash')
    )
    op.create_index('images_skinny_men_b_name_idx', 'images_skinny_men_b', ['img_skinny_name'], unique=False, postgresql_ops={'img_skinny_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_skinny_men_b_all_cats'), 'images_skinny_men_b', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_men_b_img_hash'), 'images_skinny_men_b', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_skinny_men_b_img_skinny_name'), 'images_skinny_men_b', ['img_skinny_name'], unique=False)
    op.create_index(op.f('ix_images_skinny_men_b_kind_cats'), 'images_skinny_men_b', ['kind_cats'], unique=False)
    op.create_table('images_skinny_women_b',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('img_hash', sa.String(length=40), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('img_skinny_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('img_hash')
    )
    op.create_index('images_skinny_women_b_name_idx', 'images_skinny_women_b', ['img_skinny_name'], unique=False, postgresql_ops={'img_skinny_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_skinny_women_b_all_cats'), 'images_skinny_women_b', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_attribute_cats'), 'images_skinny_women_b', ['attribute_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_color_cats'), 'images_skinny_women_b', ['color_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_filter_cats'), 'images_skinny_women_b', ['filter_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_img_hash'), 'images_skinny_women_b', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_skinny_women_b_img_skinny_name'), 'images_skinny_women_b', ['img_skinny_name'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_kind_cats'), 'images_skinny_women_b', ['kind_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_length_cats'), 'images_skinny_women_b', ['length_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_material_cats'), 'images_skinny_women_b', ['material_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_pattern_cats'), 'images_skinny_women_b', ['pattern_cats'], unique=False)
    op.create_index(op.f('ix_images_skinny_women_b_style_cats'), 'images_skinny_women_b', ['style_cats'], unique=False)
    op.create_table('prods_men_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('color_string', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_hash', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.Text(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('is_fav', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prods_men_b_image_hash'), 'prods_men_b', ['image_hash'], unique=False)
    op.create_index(op.f('ix_prods_men_b_kind_cats'), 'prods_men_b', ['kind_cats'], unique=False)
    op.create_index(op.f('ix_prods_men_b_name'), 'prods_men_b', ['name'], unique=False)
    op.create_index(op.f('ix_prods_men_b_prod_id'), 'prods_men_b', ['prod_id'], unique=True)
    op.create_table('prods_women_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('color_string', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_hash', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.Text(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('is_fav', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prods_women_b_image_hash'), 'prods_women_b', ['image_hash'], unique=False)
    op.create_index(op.f('ix_prods_women_b_kind_cats'), 'prods_women_b', ['kind_cats'], unique=False)
    op.create_index(op.f('ix_prods_women_b_name'), 'prods_women_b', ['name'], unique=False)
    op.create_index(op.f('ix_prods_women_b_prod_id'), 'prods_women_b', ['prod_id'], unique=True)
    op.create_table('images_full_men_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_hash', sa.String(length=40), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('img_full_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_1_hex', sa.String(), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2_hex', sa.String(), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3_hex', sa.String(), nullable=True),
    sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_4_hex', sa.String(), nullable=True),
    sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_5_hex', sa.String(), nullable=True),
    sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_6_hex', sa.String(), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('encoding_vgg16', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['img_hash'], ['images_skinny_men_b.img_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('images_full_men_b_name_idx', 'images_full_men_b', ['img_full_name'], unique=False, postgresql_ops={'img_full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_full_men_b_all_cats'), 'images_full_men_b', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_full_men_b_img_full_name'), 'images_full_men_b', ['img_full_name'], unique=False)
    op.create_index(op.f('ix_images_full_men_b_img_hash'), 'images_full_men_b', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_full_men_b_kind_cats'), 'images_full_men_b', ['kind_cats'], unique=False)
    op.create_table('images_full_women_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_hash', sa.String(length=40), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('img_full_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_1_hex', sa.String(), nullable=True),
    sa.Column('color_2', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_2_hex', sa.String(), nullable=True),
    sa.Column('color_3', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_3_hex', sa.String(), nullable=True),
    sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_4_hex', sa.String(), nullable=True),
    sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_5_hex', sa.String(), nullable=True),
    sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('color_6_hex', sa.String(), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('encoding_vgg16', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['img_hash'], ['images_skinny_women_b.img_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('images_full_women_b_name_idx', 'images_full_women_b', ['img_full_name'], unique=False, postgresql_ops={'img_full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_images_full_women_b_all_cats'), 'images_full_women_b', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_full_women_b_img_full_name'), 'images_full_women_b', ['img_full_name'], unique=False)
    op.create_index(op.f('ix_images_full_women_b_img_hash'), 'images_full_women_b', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_full_women_b_kind_cats'), 'images_full_women_b', ['kind_cats'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_full_women_b_kind_cats'), table_name='images_full_women_b')
    op.drop_index(op.f('ix_images_full_women_b_img_hash'), table_name='images_full_women_b')
    op.drop_index(op.f('ix_images_full_women_b_img_full_name'), table_name='images_full_women_b')
    op.drop_index(op.f('ix_images_full_women_b_all_cats'), table_name='images_full_women_b')
    op.drop_index('images_full_women_b_name_idx', table_name='images_full_women_b')
    op.drop_table('images_full_women_b')
    op.drop_index(op.f('ix_images_full_men_b_kind_cats'), table_name='images_full_men_b')
    op.drop_index(op.f('ix_images_full_men_b_img_hash'), table_name='images_full_men_b')
    op.drop_index(op.f('ix_images_full_men_b_img_full_name'), table_name='images_full_men_b')
    op.drop_index(op.f('ix_images_full_men_b_all_cats'), table_name='images_full_men_b')
    op.drop_index('images_full_men_b_name_idx', table_name='images_full_men_b')
    op.drop_table('images_full_men_b')
    op.drop_index(op.f('ix_prods_women_b_prod_id'), table_name='prods_women_b')
    op.drop_index(op.f('ix_prods_women_b_name'), table_name='prods_women_b')
    op.drop_index(op.f('ix_prods_women_b_kind_cats'), table_name='prods_women_b')
    op.drop_index(op.f('ix_prods_women_b_image_hash'), table_name='prods_women_b')
    op.drop_table('prods_women_b')
    op.drop_index(op.f('ix_prods_men_b_prod_id'), table_name='prods_men_b')
    op.drop_index(op.f('ix_prods_men_b_name'), table_name='prods_men_b')
    op.drop_index(op.f('ix_prods_men_b_kind_cats'), table_name='prods_men_b')
    op.drop_index(op.f('ix_prods_men_b_image_hash'), table_name='prods_men_b')
    op.drop_table('prods_men_b')
    op.drop_index(op.f('ix_images_skinny_women_b_style_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_pattern_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_material_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_length_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_kind_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_img_skinny_name'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_img_hash'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_filter_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_color_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_attribute_cats'), table_name='images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_women_b_all_cats'), table_name='images_skinny_women_b')
    op.drop_index('images_skinny_women_b_name_idx', table_name='images_skinny_women_b')
    op.drop_table('images_skinny_women_b')
    op.drop_index(op.f('ix_images_skinny_men_b_kind_cats'), table_name='images_skinny_men_b')
    op.drop_index(op.f('ix_images_skinny_men_b_img_skinny_name'), table_name='images_skinny_men_b')
    op.drop_index(op.f('ix_images_skinny_men_b_img_hash'), table_name='images_skinny_men_b')
    op.drop_index(op.f('ix_images_skinny_men_b_all_cats'), table_name='images_skinny_men_b')
    op.drop_index('images_skinny_men_b_name_idx', table_name='images_skinny_men_b')
    op.drop_table('images_skinny_men_b')
    # ### end Alembic commands ###
