"""empty message

Revision ID: 68c3b5849638
Revises: b0f6a1db0ec8
Create Date: 2019-10-18 00:36:01.307094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68c3b5849638'
down_revision = 'b0f6a1db0ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_v2', sa.Column('encoding_vgg16', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_index(op.f('ix_images_v2_all_cats'), 'images_v2', ['all_cats'], unique=False)
    op.drop_index('ix_images_v2_color_string', table_name='images_v2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_images_v2_color_string', 'images_v2', ['color_string'], unique=False)
    op.drop_index(op.f('ix_images_v2_all_cats'), table_name='images_v2')
    op.drop_column('images_v2', 'encoding_vgg16')
    # ### end Alembic commands ###
