"""empty message

Revision ID: 814603b8da83
Revises: 87246f5a96e6
Create Date: 2020-03-23 12:04:41.832926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814603b8da83'
down_revision = '87246f5a96e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_email_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_email_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
