"""empty message

Revision ID: 87246f5a96e6
Revises: 48b210f80d39
Create Date: 2020-03-23 11:45:13.338223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87246f5a96e6'
down_revision = '48b210f80d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_email_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_email_sent')
    # ### end Alembic commands ###
