"""empty message

Revision ID: 88df154ee637
Revises: 252a45ba03c8
Create Date: 2018-10-08 01:38:11.996793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88df154ee637'
down_revision = '252a45ba03c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instamentions', sa.Column('owner_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instamentions', 'owner_username')
    # ### end Alembic commands ###
