"""empty message

Revision ID: b3e411d03e21
Revises: f9c526088992
Create Date: 2020-01-17 12:23:26.331846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e411d03e21'
down_revision = 'f9c526088992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pw_reset_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pw_reset_token')
    # ### end Alembic commands ###
