"""empty message

Revision ID: bc21c176a90f
Revises: 40652d47de28
Create Date: 2020-03-07 19:55:45.573915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc21c176a90f'
down_revision = '40652d47de28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_v2_img_hash_fkey', 'images_v2', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('images_v2_img_hash_fkey', 'images_v2', 'images_v2_skinny', ['img_hash'], ['img_hash'])
    # ### end Alembic commands ###
