"""empty message

Revision ID: c5a6148872fb
Revises: fa748a467056
Create Date: 2020-01-23 10:21:37.584545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a6148872fb'
down_revision = 'fa748a467056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'images_v2', 'images_v2_skinny', ['img_hash'], ['img_hash'])
    op.create_foreign_key(None, 'images_v2_skinny', 'images_v2', ['img_hash'], ['img_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images_v2_skinny', type_='foreignkey')
    op.drop_constraint(None, 'images_v2', type_='foreignkey')
    # ### end Alembic commands ###
