"""empty message

Revision ID: e2b8d0cee375
Revises: b3e411d03e21
Create Date: 2020-01-19 22:09:41.484285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2b8d0cee375'
down_revision = 'b3e411d03e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_v2_skinny',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('img_hash', sa.String(length=40), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('prod_id', sa.String(), nullable=True),
    sa.Column('prod_url', sa.String(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color_string', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('img_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('saleprice', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('kind_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_pattern_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('material_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('attribute_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('filter_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('all_cats', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('size_stock', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('img_hash')
    )
    op.create_index(op.f('ix_images_v2_skinny_all_cats'), 'images_v2_skinny', ['all_cats'], unique=False)
    op.create_index(op.f('ix_images_v2_skinny_img_hash'), 'images_v2_skinny', ['img_hash'], unique=True)
    op.create_index(op.f('ix_images_v2_skinny_img_name'), 'images_v2_skinny', ['img_name'], unique=False)
    op.create_index(op.f('ix_images_v2_skinny_kind_cats'), 'images_v2_skinny', ['kind_cats'], unique=False)
    op.create_index('name_idx_v2', 'images_v2_skinny', ['img_name'], unique=False, postgresql_ops={'img_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx_v2', table_name='images_v2_skinny')
    op.drop_index(op.f('ix_images_v2_skinny_kind_cats'), table_name='images_v2_skinny')
    op.drop_index(op.f('ix_images_v2_skinny_img_name'), table_name='images_v2_skinny')
    op.drop_index(op.f('ix_images_v2_skinny_img_hash'), table_name='images_v2_skinny')
    op.drop_index(op.f('ix_images_v2_skinny_all_cats'), table_name='images_v2_skinny')
    op.drop_table('images_v2_skinny')
    # ### end Alembic commands ###
