"""empty message

Revision ID: f4a3f38b7190
Revises: 1c76adac98d0
Create Date: 2018-05-04 21:18:31.716389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4a3f38b7190'
down_revision = '1c76adac98d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color_1_hex', sa.String(), nullable=True))
    op.add_column('products', sa.Column('color_1_int', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('color_2_hex', sa.String(), nullable=True))
    op.add_column('products', sa.Column('img_cats_ai_txt', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('img_cats_sc_txt', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('nr1_cat_ai', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('nr1_cat_sc', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_color_1_int'), 'products', ['color_1_int'], unique=False)
    op.create_index(op.f('ix_products_nr1_cat_ai'), 'products', ['nr1_cat_ai'], unique=False)
    op.create_index(op.f('ix_products_nr1_cat_sc'), 'products', ['nr1_cat_sc'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_products_nr1_cat_sc'), table_name='products')
    op.drop_index(op.f('ix_products_nr1_cat_ai'), table_name='products')
    op.drop_index(op.f('ix_products_color_1_int'), table_name='products')
    op.drop_column('products', 'nr1_cat_sc')
    op.drop_column('products', 'nr1_cat_ai')
    op.drop_column('products', 'img_cats_sc_txt')
    op.drop_column('products', 'img_cats_ai_txt')
    op.drop_column('products', 'color_2_hex')
    op.drop_column('products', 'color_1_int')
    op.drop_column('products', 'color_1_hex')
    # ### end Alembic commands ###
