"""empty message

Revision ID: f8898e80094a
Revises: 814603b8da83
Create Date: 2020-03-29 10:32:57.652091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8898e80094a'
down_revision = '814603b8da83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_full_men_a', sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_men_a', sa.Column('color_4_hex', sa.String(), nullable=True))
    op.add_column('images_full_men_a', sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_men_a', sa.Column('color_5_hex', sa.String(), nullable=True))
    op.add_column('images_full_men_a', sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_men_a', sa.Column('color_6_hex', sa.String(), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_4_hex', sa.String(), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_5_hex', sa.String(), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_full_women_a', sa.Column('color_6_hex', sa.String(), nullable=True))
    op.add_column('images_skinny_men_a', sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_skinny_men_a', sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_skinny_men_a', sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_skinny_women_a', sa.Column('color_4', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_skinny_women_a', sa.Column('color_5', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('images_skinny_women_a', sa.Column('color_6', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images_skinny_women_a', 'color_6')
    op.drop_column('images_skinny_women_a', 'color_5')
    op.drop_column('images_skinny_women_a', 'color_4')
    op.drop_column('images_skinny_men_a', 'color_6')
    op.drop_column('images_skinny_men_a', 'color_5')
    op.drop_column('images_skinny_men_a', 'color_4')
    op.drop_column('images_full_women_a', 'color_6_hex')
    op.drop_column('images_full_women_a', 'color_6')
    op.drop_column('images_full_women_a', 'color_5_hex')
    op.drop_column('images_full_women_a', 'color_5')
    op.drop_column('images_full_women_a', 'color_4_hex')
    op.drop_column('images_full_women_a', 'color_4')
    op.drop_column('images_full_men_a', 'color_6_hex')
    op.drop_column('images_full_men_a', 'color_6')
    op.drop_column('images_full_men_a', 'color_5_hex')
    op.drop_column('images_full_men_a', 'color_5')
    op.drop_column('images_full_men_a', 'color_4_hex')
    op.drop_column('images_full_men_a', 'color_4')
    # ### end Alembic commands ###
