"""empty message

Revision ID: f9c526088992
Revises: fc1bc45bcbe4
Create Date: 2020-01-13 11:07:40.994117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c526088992'
down_revision = 'fc1bc45bcbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    # ### end Alembic commands ###
