"""empty message

Revision ID: fa748a467056
Revises: 901d10e3b8c0
Create Date: 2020-01-20 14:12:24.115982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa748a467056'
down_revision = '901d10e3b8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'images_v2', 'images_v2_skinny', ['img_hash'], ['img_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images_v2', type_='foreignkey')
    # ### end Alembic commands ###
