"""empty message

Revision ID: fc050074dbdc
Revises: f7edf14ae961
Create Date: 2018-06-10 17:19:15.992896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc050074dbdc'
down_revision = 'f7edf14ae961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pca_256', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pca_256')
    # ### end Alembic commands ###
