"""empty message

Revision ID: fc1bc45bcbe4
Revises: 1c6cbf3cb20d
Create Date: 2019-12-17 11:18:17.237680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1bc45bcbe4'
down_revision = '1c6cbf3cb20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loading_content', sa.Column('content_image', sa.String(), nullable=True))
    op.add_column('loading_content', sa.Column('content_text', sa.String(), nullable=True))
    op.drop_column('loading_content', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loading_content', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('loading_content', 'content_text')
    op.drop_column('loading_content', 'content_image')
    # ### end Alembic commands ###
