"""empty message

Revision ID: feeccb2ddccd
Revises: 37b0687eab49
Create Date: 2019-11-02 23:32:07.087376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feeccb2ddccd'
down_revision = '37b0687eab49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_v2', sa.Column('brand', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images_v2', 'brand')
    # ### end Alembic commands ###
